name: Upload

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: 'yarn'

    - uses: calcit-lang/setup-cr@0.0.8

    - name: "compiles to js"
      run: >
        caps --ci && cr --once js
        && yarn && yarn vite build --base=./
        && cp -r docs/assets/* dist/assets/

    - name: Deploy to server
      id: deploy
      uses: Pendect/action-rsyncer@v2.0.0
      env:
        DEPLOY_KEY: ${{secrets.rsync_private_key}}
      with:
        flags: '-avzr --progress'
        options: ''
        ssh_options: ''
        src: 'dist/*'
        dest: 'rsync-user@tiye.me:/web-assets/repo/${{ github.repository }}'

    - name: Display status from deploy
      run: echo "${{ steps.deploy.outputs.status }}"


    # also need to upload mddook

    - uses: supplypike/setup-bin@v3
      with:
        uri: 'https://github.com/rust-lang/mdBook/releases/download/v0.4.14/mdbook-v0.4.14-x86_64-unknown-linux-gnu.tar.gz'
        name: 'mdbook'
        version: '0.4.14'

    - uses: supplypike/setup-bin@v3
      with:
        uri: 'https://github.com/Michael-F-Bryan/mdbook-linkcheck/releases/download/v0.7.6/mdbook-linkcheck.x86_64-unknown-linux-gnu.zip'
        name: 'mdbook-linkcheck'
        version: '0.7.6'

    - name: mdbook build
      run: mdbook build && mv -v book/html/index.html book/html/mdbook.html

    - name: Deploy to server
      id: deploy-mdbook
      uses: Pendect/action-rsyncer@v2.0.0
      env:
        DEPLOY_KEY: ${{secrets.rsync_private_key}}
      with:
        flags: '-avzr --progress'
        options: ''
        ssh_options: ''
        src: 'book/html/*'
        dest: 'rsync-user@tiye.me:/web-assets/repo/${{ github.repository }}'

    - name: Display status from deploy
      run: echo "${{ steps.deploy-mdbook.outputs.status }}"
